### ISSUE TITLE
git-vertag: error: unknown long flag '--push-to origin', try --help

### ISSUE THREAD

**Issue by glassonion1** [kyoh86/git-vertag-action#2]
GitHub Actionsでpush: trueを設定したことろ以下のエラーが発生しました。
```
git-vertag: error: unknown long flag '--push-to origin', try --help
```
設定はこちらです。
```
     - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1.1
        with:
          # method: "major", "minor" or "patch" to update tag with semver
          method: "${{ github.event.inputs.method }}"
          push: true
```
エラーログです。
https://github.com/glassonion1/logz/runs/1662089271?check_suite_focus=true

git-vertagに--push-toフラグが無いようです。
